aplicaciones/buses/models.py
from django.db import models

# Create your models here.
class buses(models.Model):
    id = models.AutoField(primary_key= True)
    nombre = models.CharField(max_length= 80)
    placa = models.CharField(max_length= 80)
    tipo = models.CharField(max_length= 80)
    numero_de_puestos = models.CharField(max_length= 80)
    def __str__(self):
        return self.tipo

aplicaciones/principal/models.py
from django.db import models

# Create your models here.
class usuarios(models.Model):
    id = models.AutoField(primary_key= True)
    nombre = models.CharField(max_length= 80)
    apellido = models.CharField(max_length= 80)
    correo = models.CharField(max_length= 80)
    contraseña = models.CharField(max_length= 80)
    def __str__(self):
     rutas = f'{self.nombre} {self.apellido}'   
     return rutas

aplicaciones/buses/forms.py
from dataclasses import fields
from django import forms
from .models import buses

class busesForm(forms.ModelForm):
    class Meta:
        model = buses
        fields = ["id","nombre", "placa", "tipo","numero_de_puestos"]

aplicaciones/buses/views.py
from django.shortcuts import render, redirect
from .models import buses
from django.http import HttpResponse
from .forms import busesForm

def index(request):
    return render(request, "index.html", {})

def buses_urls(request):
    buse = buses.objects.all()
    return render(request, "buses/buses.html",{'buses': buse})     

def insertar_buses(request):
    if(request.method == 'GET'):
        forms = busesForm()
    else:
        forms = busesForm(request.POST)   
        if forms.is_valid():
            forms.save()
            return redirect('buses_urls')
    return render(request, 'buses/crearbuses.html' )


def editar_buses(request,id):
    buse = buses.objects.get(id = id)
    if(request.method == 'GET'):
        forms = busesForm(instance= buse)
    else:
        forms = busesForm(request.POST, instance= buse)   
        if forms.is_valid():
            forms.save()
            return redirect('buses_urls')
    return render(request, 'buses/Update_buses.html' )

def borrar_buses(request,id):
    buse = buses.objects.get(id = id)
    buse.delete()
    return redirect('buses_urls')    

templates/buses/Crearbuses.html
{% extends "menu.html" %}
{% block titulo %} Crear Pasajero {%endblock%}
{% block contenido %} 
<main>
    <html>
    <head>
         <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <meta name="copyright" content="MACode ID, https://macodeid.com">

  <title>DigiGram - Free Agency Template</title>

  <link rel="stylesheet" href="static/vendor/animate/animate.css">

  <link rel="stylesheet" href="static/css/bootstrap.css">

  <link rel="stylesheet" href="static/css/maicons.css">

  <link rel="stylesheet" href="static/vendor/owl-carousel/css/owl.carousel.css">

  <link rel="stylesheet" href="static/css/theme.css">
    </head>
 
</html>
  <div class="page-section">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-lg-6 py-3 wow fadeInUp">
            <h2 class="title-section">Get in Touch</h2>
            <div class="divider"></div>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.<br> Laborum ratione autem quidem veritatis!</p>
  
            <ul class="contact-list">
              <li>
                <div class="icon"><span class="mai-map"></span></div>
                <div class="content">123 Fake Street, New York, USA</div>
              </li>
              <li>
                <div class="icon"><span class="mai-mail"></span></div>
                <div class="content"><a href="#">info@digigram.com</a></div>
              </li>
              <li>
                <div class="icon"><span class="mai-phone-portrait"></span></div>
                <div class="content"><a href="#">+00 1122 3344 55</a></div>
              </li>
            </ul>
          </div>
          <div class="col-lg-6 py-3 wow fadeInUp">
            <div class="subhead">Contact Us</div>
            <h2 class="title-section">Drop Us a Line</h2>
            <div class="divider"></div>


    <form class="formularios" method="POST">
        {% csrf_token %}
                        {% comment %} {{form.as_p}} {% endcomment %}
                       
        <div class="titulo_formulario">
            <h1>Añadir usuarios</h1>
        </div>
        <!-- {{ form.as_p}} -->
        <div class="contenedor_input_usuario">
            <div class="mb-3 row">


                <label for="id_nombre" class="col-sm-3 col-form-label">Nombre</label>
                <div class="col-sm-9">
                    <input type="text" class="input_usuario" id="nombre_usuario id_nombre" name="nombre"
                        placeholder="Ingrese su nombre" required class="form-control">
                </div>
            </div>

        </div>
        <div class="contenedor_input_usuario">
            <div class="mb-3 row">
                <label for="id_apellido" class="col-sm-3 col-form-label">placa</label>
                <div class="col-sm-9">
                    <input type="text" class=" input_usuario" id="placa" name="placa"
                        placeholder="Ingrese su Apellido" required class="form-control">
                </div>
            </div>
        </div>
        <div class="contenedor_input_usuario">
            <div class="mb-3 row">

                <label for="id_telefono" class="col-sm-3 col-form-label">tipo</label>
                <div class="col-sm-9">
                    <input type="mail" class=" input_usuario" id="tipo" name="tipo"
                        placeholder="Ingrese su correo" required class="form-control">
                </div>
            </div>
        </div>
        <div class="contenedor_input_usuario">
            <div class="mb-3 row">

                <label for="id_correo" class="col-sm-3 col-form-label">numero de puestos</label>
                <div class="col-sm-9">
                    <input type="text" class=" input_usuario" id="numero_de_puestos" name="numero_de_puestos"
                        placeholder="Ingrese su contraseña" required class="form-control">
                </div>
            </div>
        </div>
        <div class="contenedor_input_usuario">
        </div>
      
        <button type="submit" class="btn btn-light">Ingresar usuario</button>
        <a type="button" href="buses" class="btn btn-info">Volver</a>
    </form>
</main>
</div>
</div>
</div> <!-- .container -->
</div> <!-- .page-section -->

{% endblock %}

templates/buses/Update_buses.html
{% extends "menu.html" %}
{% block titulo %} Crear Pasajero {%endblock%}
{% block contenido %} 
</html>
  <div class="page-section">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-lg-6 py-3 wow fadeInUp">
            <h2 class="title-section">Get in Touch</h2>
            <div class="divider"></div>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.<br> Laborum ratione autem quidem veritatis!</p>
  
            <ul class="contact-list">
              <li>
                <div class="icon"><span class="mai-map"></span></div>
                <div class="content">123 Fake Street, New York, USA</div>
              </li>
              <li>
                <div class="icon"><span class="mai-mail"></span></div>
                <div class="content"><a href="#">info@digigram.com</a></div>
              </li>
              <li>
                <div class="icon"><span class="mai-phone-portrait"></span></div>
                <div class="content"><a href="#">+00 1122 3344 55</a></div>
              </li>
            </ul>
          </div>
          <div class="col-lg-6 py-3 wow fadeInUp">
            <div class="subhead">Contact Us</div>
            <h2 class="title-section">Drop Us a Line</h2>
            <div class="divider"></div>


    <form class="formularios" method="POST">
        {% csrf_token %}
                        {% comment %} {{form.as_p}} {% endcomment %}
                       
        <div class="titulo_formulario">
            <h1>Añadir usuarios</h1>
        </div>
        {{ form.as_p}} 
        <div class="contenedor_input_usuario">
            <div class="mb-3 row">


                <label for="id_nombre" class="col-sm-3 col-form-label">Nombre</label>
                <div class="col-sm-9">
                    <input type="text" class="input_usuario" id="nombre_usuario id_nombre" name="nombre"
                        placeholder="Ingrese su nombre" required class="form-control">
                </div>
            </div>

        </div>
        <div class="contenedor_input_usuario">
            <div class="mb-3 row">
                <label for="id_apellido" class="col-sm-3 col-form-label">placa</label>
                <div class="col-sm-9">
                    <input type="text" class=" input_usuario" id="placa" name="placa"
                        placeholder="Ingrese su Apellido" required class="form-control">
                </div>
            </div>
        </div>
        <div class="contenedor_input_usuario">
            <div class="mb-3 row">

                <label for="id_telefono" class="col-sm-3 col-form-label">tipo</label>
                <div class="col-sm-9">
                    <input type="mail" class=" input_usuario" id="tipo" name="tipo"
                        placeholder="Ingrese su correo" required class="form-control">
                </div>
            </div>
        </div>
        <div class="contenedor_input_usuario">
            <div class="mb-3 row">

                <label for="id_correo" class="col-sm-3 col-form-label">numero de puestos</label>
                <div class="col-sm-9">
                    <input type="text" class=" input_usuario" id="numero_de_puestos" name="numero_de_puestos"
                        placeholder="Ingrese su contraseña" required class="form-control">
                </div>
            </div>
        </div>
        <div class="contenedor_input_usuario">
        </div>
      
        <button type="submit" class="btn btn-light">Ingresar usuario</button>
        <a type="button" href="buses" class="btn btn-info">Volver</a>
    </form>
</main>
</div>
</div>
</div> <!-- .container -->
</div> <!-- .page-section -->

{% endblock %}

templates/buses/buses.html
 {% extends "menu.html" %}
 {% block titulo %} Crear Pasajero {%endblock%}
 {% block contenido %} 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
  
    <title>iPortfolio Bootstrap Template - Index</title>
    <meta content="" name="description">
    <meta content="" name="keywords">
    <!-- Favicons -->
    
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <!-- Bootstrap DataTable -->
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css">
  <!-- Bootstrap ExportDataTable -->
  <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.0/css/buttons.bootstrap.min.css">
  <!-- Font icons -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <!-- jQuery -->
  <script type="text/javascript" src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <!-- DataTables JS -->
  <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js"></script>
  <!--  ExportDataTable JS -->
  <script src="https://cdn.datatables.net/buttons/1.5.0/js/dataTables.buttons.min.js"></script>
  <script src="https://cdn.datatables.net/buttons/1.5.0/js/buttons.bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
  <script src="https://cdn.datatables.net/buttons/1.5.0/js/buttons.html5.min.js"></script>
  <script src="https://cdn.datatables.net/buttons/1.5.0/js/buttons.print.min.js"></script>
  <script src="https://cdn.datatables.net/buttons/1.5.0/js/buttons.colVis.min.js"></script>
  <!-- Bootstrap JS -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script type="text/javascript">
  $(document).ready(function() {
      var table = $('#ExportDataTable').DataTable( {
          lengthChange: false,
          //buttons: [ 'copy', 'excel', 'pdf', 'print', 'colvis' ]
          buttons: [ 'copy', 'excel', 'pdf', 'print']
      } );
      table.buttons().container()
          .appendTo( '#ExportDataTable_wrapper .col-sm-6:eq(0)' );
  } );
  </script>
 <title>JSP Page</title>
</head>
<body>
    <div class="page-section">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 py-3 wow fadeInUp">
        <h2 class="title-section">Get in Touch</h2>
        <div class="divider"></div>
        
    
    
    <div>
    <a href="insertar_buses" type="button" class="btn btn-primary">Añadir Usuario</a>
    <table id="ExportDataTable" class="table table-striped table-hover table-bordered" cellspacing="0" width="100%">
        <thead>
      <tr class="text-center">
                <th>ID</th>
                <th>Nombre</th>
                <th>Placa</th>
                <th>Tipo</th>
                <th>Numero de puestos</th>
                <th>Acciones</th>
                <th>Acciones</th>
    
            </tr>
        </thead>
      <tbody>
     {% for buse in buses %}
        <tr class="text-center">
            <td>{{buse.id}}</td> 
            <td>{{buse.nombre}}</td>
            <td>{{buse.placa}}</td>
            <td>{{buse.tipo}}</td>
            <td>{{buse.numero_de_puestos}}</td>
            <td><a href="editar_buses/{{buse.id}}" type="button" class="btn btn-warning">Modificar</a>
            </td>
            <td><a onclick="return confirm('esta seguro que desea borrar el buse');"  href="borrar_buses/{{buse.id}}" type="button" class="btn btn-danger">Eliminar</a></td></td>
            </tr>
     {% endfor %}
        </tbody>
    </table>
</div>
        
                   
</div>
</div>
</div> <!-- .container -->
</div> <!-- .page-section -->


</body>
</html>
{%endblock%}